runtime: python
env: flex
entrypoint: entrypoint: gunicorn -b :$PORT app:app

handlers:
    -url: /.*
    script: app.app

runtime_config:
    python_version: 3

env_variables:
    SPOTIFY_SETTINGS: "config.ProductionConfig"