runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /.*
  http_headers:
    Access-Control-Allow-Origin: http://localhost:8080/

runtime_config:
    python_version: 3

env_variables:
    SPOTIFY_SETTINGS: "config.ProductionConfig"