runtime: python
env: flex
entrypoint: entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /.*
  http_headers:
    Access-Control-Allow-Origin: *

runtime_config:
    python_version: 3

env_variables:
    SPOTIFY_SETTINGS: "config.ProductionConfig"