runtime: python
env: flex
entrypoint: uwsgi --http :$PORT --wsgi-file app.py --callable app

handlers:
    -url: /.*
    script: app.py

runtime_config:
    python_version: 3

env_variables:
    SPOTIFY_SETTINGS: "config.ProductionConfig"